name: petspector
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.2.0
  tflite_flutter: ^0.11.0
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  google_sign_in: ^7.2.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  
  # Supabase
  supabase_flutter: ^2.0.0

  # Camera
  camera: ^0.11.2

  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/ps_icon.png
    - assets/images/ps_logo.png
    - assets/images/google_logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ps_icon.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  image_path: "assets/images/ps_icon.png"
  remove_alpha_ios: true
