name: petspector
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  tflite_flutter: ^0.10.4
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  google_sign_in: ^6.1.4
   # Firebase core
  firebase_core: ^3.6.0
  # Firebase Authentication
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12 # if you need a database
  flutter_native_splash: ^2.4.1
  firebase_storage: ^12.3.3
  supabase_flutter: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ps_icon.png
    - assets/images/ps_logo.png
    - assets/images/google_logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"            # background color of your splash screen
  image: assets/images/ps_icon.png   # path to your splash logo
  android: true
  ios: true
  web: true      

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  image_path: "assets/images/ps_icon.png"
  remove_alpha_ios: true



