// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvYBL87PTk2kVsW52yx3DH04hhir5o8E',
    appId: '1:96102123175:web:666ae72fd11feff194fd82',
    messagingSenderId: '96102123175',
    projectId: 'petspector-d3e39',
    authDomain: 'petspector-d3e39.firebaseapp.com',
    storageBucket: 'petspector-d3e39.firebasestorage.app',
    measurementId: 'G-WHDXEHJ30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb03dH7I43CXjrHpeOMukHu2tbmuK9Epc',
    appId: '1:96102123175:android:c047d340afff6e4d94fd82',
    messagingSenderId: '96102123175',
    projectId: 'petspector-d3e39',
    storageBucket: 'petspector-d3e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRZnDmH5oNJ-UnaG-dX_iUpenPNBdu6k',
    appId: '1:96102123175:ios:8922b658974ac57a94fd82',
    messagingSenderId: '96102123175',
    projectId: 'petspector-d3e39',
    storageBucket: 'petspector-d3e39.firebasestorage.app',
    iosBundleId: 'com.jmprz.petspector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRZnDmH5oNJ-UnaG-dX_iUpenPNBdu6k',
    appId: '1:96102123175:ios:8922b658974ac57a94fd82',
    messagingSenderId: '96102123175',
    projectId: 'petspector-d3e39',
    storageBucket: 'petspector-d3e39.firebasestorage.app',
    iosBundleId: 'com.jmprz.petspector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZvYBL87PTk2kVsW52yx3DH04hhir5o8E',
    appId: '1:96102123175:web:121d962c1ccdc84e94fd82',
    messagingSenderId: '96102123175',
    projectId: 'petspector-d3e39',
    authDomain: 'petspector-d3e39.firebaseapp.com',
    storageBucket: 'petspector-d3e39.firebasestorage.app',
    measurementId: 'G-S5LNJSJT1S',
  );
}
